### ISSUE TITLE
Omas' onboarding checklist

### ISSUE THREAD

**Issue by omasabdullah** [omasabdullah/omasabdullah#13]
### Set up your company email account

- [x] I have set up my company email account

### Complete your profile on the company intranet

- [x] I have completed my profile on the intranet

### Join the team chat platform and introduce yourself

- [x] I have joined the chat and introduced myself

### Review the company policies and handbook

- [ ] I have reviewed the company policies and handbook

### Schedule a one-on-one with your manager

- [ ] I have scheduled a one-on-one with my manager

### Set up your work environment and tools

- [ ] I have set up my work environment and tools
